// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateCode(arg1:string):Promise<string>;

export function RunWorkflow(arg1:Array<main.NodeData>):Promise<string>;
