// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateCode(arg1) {
  return window['go']['main']['App']['GenerateCode'](arg1);
}

export function RunWorkflow(arg1) {
  return window['go']['main']['App']['RunWorkflow'](arg1);
}
